version: '3.8'
services:
  inventory-db:
    image: redis:6.2-alpine
    container_name: inventory-db-container
    hostname: inventory-db
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass invDbPass
    volumes: 
      - inventory-cache:/data
  orders-db:
    image: redis:6.2-alpine
    container_name: orders-db-container
    hostname: orders-db
    restart: always
    ports:
      - '6378:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ordersDbPass
    volumes: 
      - orders-cache:/data
  users-db:
    image: redis:6.2-alpine
    container_name: users-db-container
    hostname: users-db
    restart: always
    ports:
      - '6377:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass usersDbPass
    volumes: 
      - users-cache:/data
  eventq:
    image: redis:6.2-alpine
    container_name: eventq-container
    hostname: eventq
    restart: always
    ports:
      - '6376:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eventqPass
volumes:
  inventory-cache:
    driver: local
  orders-cache:
    driver: local
  users-cache:
    driver: local
